vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g== # to add C/C++ extension

tasks:
  - before: pip3 install -U platformio
    command: platformio run -e eval_f072vb # where eval_f072vb is my variable
